# -*- coding: utf-8 -*-
"""Global_Layoffs_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNGWEvNZrcpbLopskFJ4VNuijTfGienU
"""

import numpy as pandas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

data = pd.read_csv("/content/layoffs.csv")

data.head()

data.columns

data.shape

data.info()

for col in data.columns:
  print(f"{col} -> {data[col][0]}")

data.isnull().sum()[data.isnull().sum() > 0]

data["date"] = pd.to_datetime(data["date"])

data["date_added"] = pd.to_datetime(data["date_added"])

data.describe()

"""data.duplicated().sum()"""

data.drop_duplicates()

data["company"] = data["company"].str.strip()

data["country"].unique()

data.fillna({"country":"unknown"}, inplace=True)

data.isnull().sum()[data.isnull().sum() > 0]

data["location"].fillna("unknown", inplace=True)

data["total_laid_off"].fillna(data["total_laid_off"].mean(), inplace=True)

data["percentage_laid_off"].fillna(data["percentage_laid_off"].mean(), inplace=True)

data["industry"].fillna("unknown", inplace=True)
data["source"].fillna("unknown", inplace=True)
data["stage"].fillna("unknown", inplace=True)

data["funds_raised"].fillna(data["funds_raised"].mean(), inplace=True)

data.isnull().sum()[data.isnull().sum() > 0]

"""### Feature Engineering"""

data['month'] = data['date'].dt.month
data['year'] = data['date'].dt.year
data['date_added_month'] = data['date_added'].dt.month
data['date_added_year'] = data['date_added'].dt.year


data['days_since_added'] = (data['date_added'] - data['date']).dt.days

display(data.head())

"""### Data Visualization and Exploration

Let's start by visualizing the companies with the highest number of total layoffs.
"""

# Top 10 companies by total_laid_off
top_companies = data.groupby('company')['total_laid_off'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_companies.index, y=top_companies.values, palette='viridis')
plt.title('Top 10 Companies by Total Layoffs')
plt.xlabel('Company')
plt.ylabel('Total Layoffs')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Next, let's look at the trend of layoffs over time, specifically by year."""

# Layoffs trend over time (by year)
layoffs_by_year = data.groupby('year')['total_laid_off'].sum().reset_index()

plt.figure(figsize=(10, 5))
sns.lineplot(x='year', y='total_laid_off', data=layoffs_by_year, marker='o')
plt.title('Total Layoffs Over the Years')
plt.xlabel('Year')
plt.ylabel('Total Layoffs')
plt.grid(True)
plt.xticks(layoffs_by_year['year'].unique())
plt.tight_layout()
plt.show()

"""Let's also look at the total layoffs by industry to identify which sectors have been most affected."""

# Total layoffs by industry
layoffs_by_industry = data.groupby('industry')['total_laid_off'].sum().nlargest(15).sort_values(ascending=False)

plt.figure(figsize=(14, 7))
sns.barplot(x=layoffs_by_industry.index, y=layoffs_by_industry.values, palette='magma')
plt.title('Top 15 Industries by Total Layoffs')
plt.xlabel('Industry')
plt.ylabel('Total Layoffs')
plt.xticks(rotation=60, ha='right')
plt.tight_layout()
plt.show()

"""Now, let's analyze the total layoffs by country to see which regions have been most impacted."""

# Total layoffs by country
layoffs_by_country = data.groupby('country')['total_laid_off'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=layoffs_by_country.index, y=layoffs_by_country.values, palette='plasma')
plt.title('Top 10 Countries by Total Layoffs')
plt.xlabel('Country')
plt.ylabel('Total Layoffs')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Let's examine the distribution of `total_laid_off` and `percentage_laid_off` to understand their characteristics."""

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
sns.histplot(data['total_laid_off'], bins=50, kde=True)
plt.title('Distribution of Total Laid Off')
plt.xlabel('Total Laid Off')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
sns.histplot(data['percentage_laid_off'], bins=30, kde=True)
plt.title('Distribution of Percentage Laid Off')
plt.xlabel('Percentage Laid Off')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

# Average percentage laid off by stage
layoffs_by_stage = data.groupby('stage')['percentage_laid_off'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x=layoffs_by_stage.index, y=layoffs_by_stage.values, palette='cubehelix')
plt.title('Average Percentage Laid Off by Company Stage')
plt.xlabel('Company Stage')
plt.ylabel('Average Percentage Laid Off')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

